[window]
decorations = "none"
padding = { x = 15, y = 15 }
dynamic_padding = true
startup_mode = "Windowed"
dimensions = { columns = 80, lines = 24 }
opacity = 1.00

[font]
size = 10
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }

builtin_box_drawing = true
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 1 }

[cursor]
style = { shape = "Block", blinking = "On" }

[env]
TERM = "xterm-256color"
SHELL = "/bin/zsh"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[general]
live_config_reload = true

[debug]
persistent_logging = false
 

#####################
## Rose Pine Theme ##
#####################
[colors.primary]
background = '#191724'
foreground = '#e0def4'

[colors.cursor]
text = '#e0def4'
cursor = '#524f67'

[colors.vi_mode_cursor]
text = '#e0def4'
cursor = '#524f67'

[colors.selection]
text = '#e0def4'
background = '#403d52'

[colors.normal]
black = '#26233a'
red = '#eb6f92'
green = '#31748f'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ebbcba'
white = '#e0def4'

[colors.bright]
black = '#6e6a86'
red = '#eb6f92'
green = '#31748f'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ebbcba'
white = '#e0def4'

[colors.hints]
start = {foreground = '#908caa', background = '#1f1d2e' }
end = { foreground = '#6e6a86', background = '#1f1d2e' }
